### ISSUE TITLE
Call to undefined function GetSignatureImage()

### ISSUE THREAD

**Issue by anthonycanol** [wp-premium/gravityformssignature#1]
recently experienced an "The site is experiencing Technical Difficulties" error after submitting the form.. turning on the debug on wordpress point to this error, Call to undefined function GetSignatureImage()

**Comment by remcotolsma** [comment]
> Gravity Forms Signature Add-On, Git-ified. Synced manual! This repository is just a mirror of the Gravity Forms Signature Add-On plugin. **Please do not send pull requests and issues.**
