### ISSUE TITLE
GF_Signature_Url mentioned but not available

### ISSUE THREAD

**Issue by opcoach** [wp-premium/gravityformssignature#2]
This function is mentioned as deprecated : 

  /**
         * Returns the URL for the specified signature.
         *
         * @deprecated 4.0
         *
         * @param string $filename The filename for this signature.
         *
         * @return string
         */
        public function get_signature_url( $filename ) {
                _deprecated_function( __METHOD__, '3.10', 'GF_Signature_Url::get_url()' );

                $path_info = pathinfo( $filename );
                $filename  = $path_info['filename'];

                return site_url() . "?page=gf_signature&signature={$filename}";
        }

but there is no class GF_Signature_Url ?

**Comment by remcotolsma** [comment]
> Gravity Forms Signature Add-On, Git-ified. Synced manual! This repository is just a mirror of the Gravity Forms Signature Add-On plugin. **Please do not send pull requests and issues.**
